// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGv80SbUfrW_AAAzYNJkOrn2qdg8qrEik',
    appId: '1:968270815166:web:92da0115c425bcf373a3ef',
    messagingSenderId: '968270815166',
    projectId: 'gvy-flutter',
    authDomain: 'gvy-flutter.firebaseapp.com',
    storageBucket: 'gvy-flutter.appspot.com',
    measurementId: 'G-B07L0JLM4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkE5Nq5Fl-Fv0502DpD10oHVnZt46V98w',
    appId: '1:968270815166:android:038f7c016d41f13773a3ef',
    messagingSenderId: '968270815166',
    projectId: 'gvy-flutter',
    storageBucket: 'gvy-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp8ryAFxcQJUTdhyIwAYGh5VcHGLhGOAM',
    appId: '1:968270815166:ios:e8befd4d13b3dcc873a3ef',
    messagingSenderId: '968270815166',
    projectId: 'gvy-flutter',
    storageBucket: 'gvy-flutter.appspot.com',
    iosClientId: '968270815166-8djime2l00f5rolcg8onoaaurbrt0hnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterColarx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp8ryAFxcQJUTdhyIwAYGh5VcHGLhGOAM',
    appId: '1:968270815166:ios:e8befd4d13b3dcc873a3ef',
    messagingSenderId: '968270815166',
    projectId: 'gvy-flutter',
    storageBucket: 'gvy-flutter.appspot.com',
    iosClientId: '968270815166-8djime2l00f5rolcg8onoaaurbrt0hnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterColarx',
  );
}
